version: '3.5'

services:
  db:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - ./resources/database-data:/var/lib/postgresql/data/

  web:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080
    restart: on-failure
    volumes:
      - ./resources/apps/downloads:/app/resources

  nginx:
    image: nginx:latest
    ports:
      - 4000:4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  default:
    driver: bridge
    name: common